- tasks/abs.rb
abs provision now stores job_id and platform in inventory for use by teardown method
> (maint) - abs teardown method now works correctly

- README.md
- tasks/vagrant.json
- tasks/vagrant.rb
`bundle exec rake 'litmus:provision[vagrant, ubuntu14.04]'`
> Add vagrant provisioner

- tasks/vagrant.rb
This appears to just not work at all if it's a relative path for me. Presumably its' something about my setup but there's no harm in making it absolute
> Changed to absolute path

- tasks/vagrant.rb
Prior to this commit attempting to provision a Windows VM would
sometimes fail in an unclear way; this code relies on the vagrant
command, winrm-config, to retrieve the information for connecting
to a Windows machine.
This functionality was introduced in Vagrant 2.2.0:
- https://github.com/hashicorp/vagrant/blob/master/CHANGELOG.md#220-october-16-2018
This commit adds a memoized version check for vagrant as well as
a verification that the version of vagrant being used supports
provisioning Windows nodes if attempting to do so; if the task
is attempting to provision a Windows node on an unsupported
version of Vagrant it now fails loudly and clearly.
> (MODULES-10045) Add check/alert for vagrant version

- tasks/docker.rb
sometimes the redhat 6 variant containers like to eat their rpmdb, leading to
issues with "rpmdb: unable to join the environment" errors
This "fix" is recommended across many forum posts with no specific cause analysis.
for example: https://www.srv24x7.com/criticalyum-main-error-rpmdb-open-failed/
> (maint) force rebuild of rpmdb

- tasks/vagrant.json
- tasks/vagrant.rb
Added the following optional parameters to the vagrant task:
provider, cpus, memory
> (MODULES-10415) add params for vagrant: provider, cpus & memory

- tasks/docker.json
- tasks/docker.rb
Similar to docker_exp provisioner, this makes docker provisioner to respect vars from the `provision.yml`.
> Add vars support to the docker provisioner

- README.md
- tasks/fix_secure_path.json
- tasks/fix_secure_path.sh
- tasks/vagrant.rb
add puppet agent bin directory to sudo secure path
> Sudo secure path patch

- .gitignore
- .rubocop.yml
- .travis.yml
- .vscode/extensions.json
- Rakefile
- metadata.json
- spec/spec_helper.rb
(maint) - Pdk Update
pdk version: `1.17.0`
> pdksync - (maint) - Pdk Update

- tasks/abs.rb
Resolves an issue with the ABS provisioner where it would rapidly
retry requests to the ABS API in a quick loop, then fail.
We make a request for our VMs and expect to receive a HTTP 202 by
the API to indicate it is servicing our request. We then go in to
a retry loop for 10 minutes, sleeping 5 secs and doubling each loop
until we hit 60 seconds. We will then break out of the loop when
either of these conditions are met:
- HTTP 200: Indicating successful provisioning
- HTTP 404: Indicating no further queries should be attempted
We will raise a unique alert for each failure condition.
> (IAC-822) Improve robustness of ABS API retry loop

- tasks/abs.rb
The change in https://github.com/puppetlabs/provision/pull/116 was weighted too heavily towards not saturating
the ABS API, at a higher cost to provisioning time. This commit aims
to strike a better balance between speed / API calls.
> (maint) Tune timeout loop in ABS provisioner to increase speed

- tasks/abs.rb
Use detailed info from CI environments if available
> Improve tagging in ABS provisioner

- tasks/abs.rb
Also added timestamps to API responses for better debugging.
See this Slack thread for more info: https://puppet.slack.com/archives/CF418R4BE/p1596738398297600
**Tests:**
```
bundle exec bolt --modulepath /Users/ciaran.mccrisken/sanfrancrisko/provision/spec/fixtures/modules task run provision::abs action=provision platform=ubuntu-1604-x86_64 inventory=/tmp --targets localhost
Started on localhost...
Finished on localhost:
2020/08/07 12:59:53: Received: 202 Accepted from ABS
2020/08/07 12:59:55: Received 202 Accepted from ABS
2020/08/07 12:59:57: Received 202 Accepted from ABS
2020/08/07 13:00:01: Received 202 Accepted from ABS
2020/08/07 13:00:05: Received 202 Accepted from ABS
2020/08/07 13:00:11: Received 202 Accepted from ABS
2020/08/07 13:00:17: Received 202 Accepted from ABS …
```
> (maint) Remove spaces from job ID

- .rubocop.yml
- lib/task_helper.rb
- metadata.json
- spec/unit/task_helper_spec.rb
- tasks/abs.rb
- tasks/docker.rb
- tasks/docker_exp.rb
- tasks/provision_service.rb
- tasks/run_tests.rb
- tasks/update_node_pp.rb
- tasks/update_site_pp.rb
- tasks/vagrant.rb
- tasks/vmpooler.rb
Will allow #143 to be merged after it's rebased with these fixes
> (maint) Fix Rubocop violations for target Ruby version of 2.4

- README.md
The Litmus wiki isn't used anymore.
> README.md: update link to Litmus documentation; spelling corrections

- README.md
- tasks/update_node_pp.rb
- tasks/vagrant.rb
Removal of any inappropriate or offensive terminology from the code base.
> (IAC-1022) - Removal of Inappropriate Terminology

- tasks/install_puppetserver.json
- tasks/install_puppetserver.sh
The puppetserver_install task is now able to install puppetserver on different platforms
> new install_puppetserver.sh task

- .gitignore
- .gitpod.yml
- .pdkignore
- .rubocop.yml
- .travis.yml
- metadata.json
- spec/spec_helper.rb
(maint) Running pdk update
pdk version: `2.0.0`
> pdksync - (maint) Running pdk update

- README.md
- tasks/vagrant.json
- tasks/vagrant.rb
* Add Vagrant `box_url` option
* Add Vagrant `password` option
* Fix task error type typo
> Add vagrant options

- tasks/vagrant.rb
Add support for RHEL, Oracle Linux, and SLES
> Add Vagrant provisioner compatibility for additional distros

- tasks/docker.rb
This changes how SSH forwarding ports are allocated when provisioning a Docker container. This changes port allocation to pick an arbitrary port number at random from the ephemeral port range, tests to see if the port is in use or not with a socket connection, and assigns the port if it is not in use.
This change allows for a large amount of containers to be provisioned as opposed to the 8 allowed beforehand due to the hard-coded port range. Additionally, this change moves the ports used from the well-known range to the ephemeral range reducing the potential for port conflicts.
> Docker SSH forwarding port allocations

- tasks/docker_exp.rb
Prior to this, a pdk validation error was corrected to use the include method. This PR implements this method properly as the ? was missed
> (CONT-953) Fix bad include method

- .github/workflows/release_prep.yml
> (maint) - add version input to release_prep

- README.md
> (MAINT) - readme updates

- .github/workflows/ci.yml
- tasks/install_pe.sh
- tasks/install_puppetserver.sh
* cleanup shellcheck issue in current scripts
* mark internal use tasks as private
> add shellcheck to CI

- tasks/provision_service.rb
> (MAINT) typo fix in message
