puppetlabs/provision

tasks/docker.rb

When provisioning Debian9 and Ubuntu16/18 you need to pass in ```--volume
/sys/fs/cgroup:/sys/fs/cgroup:ro``` to the command to provision.
This has been tested on the following to ensure breakages haven't been introduced.
- Ubuntu14
```➜  puppetlabs-mysql git:(litmus_conversion) ✗ bundle exec ruby spec/fixtures/modules/provision/tasks/docker.rb
{ "platform": "waffleimage/ubuntu14.04", "action": "provision", "inventory": "/Users/paula/workspace/puppetlabs-mysql" }
!!! Using private port forwarding!!!
docker run -d -it  --privileged -p 2225:22 --name waffleimage_ubuntu14.04_-2225 waffleimage/ubuntu14.04 
{"status":"ok","node_name":"localhost:2225"} 
```
- Ubuntu16
```➜ puppetlabs-mysql git:(litmus_conversion) ✗ bundle exec ruby spec/fixtures/modules/provision/tasks/docker.rb
{ "platform": …
```

(bugfix) - Add volume parameter for Debian9 and Ubuntu16/18

---

tasks/docker.rb

Single quotes as used prior to this change will not work when the docker
commands are executed from Windows. This change switches to using escaped double
quotes so that the commands can be successfully run from a Windows workstation.

Fix Escaping on Windows

---

README.md
tasks/vagrant.json
tasks/vagrant.rb

This commit adds support to the Vagrant provisioner for
using the Hyper-V provider on windows. Right now it does
not do a smart determination of provider - if Windows,
use Hyper-V, else use VirtualBox.
It also adds three new parameters:
- `hyperv_vswitch` to specify which virtual switch the
VM should be attached to. Note that if this is not
specified it will attempt to use the `Default Switch`
which is present on all Windows 10 (v1709+) machines.
- `hyperv_smb_username` and `hyperv_smb_password` which
are required to automatically share the folder with
the VM.
Without specifying both the switch and the SMB username
and password the task would fail as it cannot accept
any input in the context in which `bolt task run` has
to execute.
This commit updates the task, metadata, and …

(FM-8178) Add Hyper-V Vagrant Support

---

tasks/docker.rb

Previously in commit 36239947 much of the escaping was fixed however the RSA key for CentOS was missed.  Without this change testing CentOS on Windows is impossible.

(maint) Fix more escaping on Windows

---

Gemfile
lib/task_helper.rb
tasks/vagrant.rb

Prior to this commit the detection for whether or not a target uses is SSH is *actually* a proxy for "is the target a windows node" by checking if the name of the platform includes "win-".
This PR updates the check in two important ways:
1. It moves the check logic to a more correctly named method, `platform_is_windows?` which is clear about what it is checking. This check is still not perfect as it checks on platform name, which is not perfectly reliable.
2. The regex for the name check is improved and documented.
Also prior to this PR, the task used a method, `configure_ssh`, to retrieve the connection information for a target host after vagrant spins the machine up. It did this regardless of whether or not the target has SSH enabled or is a Windows machine. This caused errors when …

(FM-8274) Ensure vagrant task can provision Windows targets

---

tasks/docker_exp.rb

The append_cli parameter needs to be posisioned before the name of docker image to be run.

(bugfix) Fix location of append_cli in docker command

---

tasks/vagrant.json
tasks/vagrant.rb

Prior to this commit the default behavior of vagrant machines
provisioned with the vagrant task used the synced_folder
functionality. This functionality is not used by Litmus but
might be used in other cases.
On Windows, when using the Hyper-V provider for Vagrant, it
is required to also specify a username and password for the
synced_folder. This causes provisioning runs on windows to
often fail by default if the user does not specify credentials.
This commit will cause the default behavior on Windows to
fail less while still enabling workflows that require a
synced folder.

(FM-8260) Disable vagrant synced folders by default

---

tasks/abs.rb
tasks/docker.rb
tasks/docker_exp.rb
tasks/vagrant.rb
tasks/vmpooler.rb

This means that if a plan wants to provision a node and use it right away it can do so with the data that is returned by the task, without having to go back to the inventory and re-read it.

Added node object to return data

---

tasks/vagrant.rb

Anything that gets printed to STDOUT other than JSON breaks the functionality. Needs to be STDERR

Removed all STDOUT except JSON results

---

tasks/vagrant.rb

Prior to this commit the vagrant task would look for environment
variables prepended with LITMUS_ and use them to set params.
This commit modifies the expected ENV variables to be prepended
with VAGRANT_ instead as this module is not litmus-specific
but these variables *are* vagrant-specific.

(MODULES-9845) Correct vagrant env variable names

---

tasks/abs.rb
tasks/docker.rb
tasks/docker_exp.rb
tasks/vagrant.rb
tasks/vmpooler.rb

Prior to this commit the provisioning tasks allowed a user
to specify both node_name and platform even though those
variables are and should be exclusive parameter sets.
This commit updates the provisioning tasks to raise an
error if both parameters are specified.

(FM-8344) Error on exlusive params

---

tasks/docker.rb

Fedora 30 is out and doesn't match the regex. This might break Fedora 21 or older, but those are EOL. It also uses ssh-keygen -A to automatically generate all host keys.
Debian, Ubuntu and Cumulus are the same and can be one block.

Clean up SSH setup on docker provisioning

---

lib/task_helper.rb
tasks/abs.rb
tasks/docker.rb
tasks/docker_exp.rb
tasks/vagrant.rb
tasks/vmpooler.rb

Previously the provision tasks stated that the inventory parameter was optional
however if you don't pass this parameter it raises Runtime Errors as you can't
File.join on nil. This commit adds a helper to sanitise the inventory location
and return the current working directory if none is specified.
This commit also cleans up the task_helper to only require libraries it requires
instead of pulling in entire libraries (e.g. litmus) even if they're never used.

(maint) Use a default for inventory location

---

tasks/docker_exp.json
tasks/docker_exp.rb

This commit updates the `docker_exp` provisioner with the ability to add
variables set in `provision.yaml` to node entries generated for inventory.yaml.
Logic has been copied from the existing implementation in the `vmpooler` provisioner.

Add vars support to the docker_exp provisioner

---

tasks/docker.rb

Since regular users do not have access to the ESM (https://ubuntu.com/esm),
it's more useful here to remove the source and carry on, rather than abort.
This does make the ubuntu:14.04 image unusable for public use

(maint) remove ESM apt source for ubuntu 14.04

---

tasks/docker.rb

When running command `bundle exec rake 'litmus:provision[docker, centos:7]'`, as instructed in the tutorial on https://github.com/puppetlabs/puppet_litmus/wiki/Tutorial:-use-Litmus-to-execute-acceptance-tests-with-a-sample-module-(MoTD)#provision-a-target-to-test-against, I get this error on Windows 10:
```
{"target"=>"localhost", "action"=>"task", "object"=>"provision::docker", "status"=>"failure", "result"=>{"_error"=>{"kind"=>"facter_task/failure", "msg"=>"Attempted to run\ncommand:'docker exec centos_7-2222 bash -exc 'rm -f /var/lib/rpm/__db*; db_verify /var/lib/rpm/Packages; rpm --rebuilddb; yum clean all; yum install -y sudo openssh-server openssh-clients''\nstdout:\nstderr:-f: -c: line 0: unexpected EOF while looking for matching `''\n"}}, "node"=>"localhost"}
```
This pull request …

Fix quoting on centos docker provisioning. Solves "unexpected EOF while looking for matching `''" error on Windows 10

---

lib/task_helper.rb
spec/unit/task_helper_spec.rb

Prior to this commit any specified platform whose name included
Windows rather than windows would fail to be identified as
a Windows machine properly and thereby fail unpredictably.
This commit downcases the platform prior to the comparison.

(MAINT) Downcase platform for windows regex check

---

tasks/vagrant.rb

In #101 code was introduced to enable provisioning in folders with spaces; however, the interpolation of quotes on windows lead to a failure. This commit updates the quote interpolation to use double quotes, fixing the task on Windows.

(MAINT) Fix vagrant provision on Windows

---

tasks/abs.rb

The ABS API has the ability to set the [priority level](https://github.com/puppetlabs/always-be-scheduling#priority-queuing) of a job. When running in the context of a CI run, we will keep the priority level at 2, however, when running from a manually triggered test run, we'll request priority 1.
Closes: #122

Make use of ABS Priority Queuing

---

tasks/abs.json
tasks/abs.rb

This is the same as how it works for VMPooler provisioning:
```
➜  joe git:(CISC-611) ✗ bundle exec bolt --modulepath spec/fixtures/modules  plan run joe::demo_01_provision_machines
Bolt may be installed as a gem. To use Bolt reliably and with all of its
dependencies, uninstall the 'bolt' gem and install Bolt as a package:
https://puppet.com/docs/bolt/latest/bolt_installing.html
If you meant to install Bolt as a gem and want to disable this warning,
set the BOLT_GEM environment variable.
Starting: plan joe::demo_01_provision_machines
Starting: task provision::abs on localhost
Finished: task provision::abs with 0 failures in 5.69 sec
Starting: task provision::abs on localhost
Finished: task provision::abs with 0 failures in 5.8 sec
Starting: task provision::abs on localhost
Finished: task …
```

(feat) allow ABS to accept bolt vars

---

tasks/vagrant.rb

This means that conflict detection works as anticipated when boxes have a slash in their name

Strip slashes from directories

---

tasks/abs.rb

The API URL for ABS has changed as of `2020-09-17` to abs-prod.k8s.infracore.puppet.net

(maint) Update ABS API URI

---

README.md
tasks/provision_service.json
tasks/provision_service.rb

Bolt task for provision service

---

tasks/docker.rb

This started from a talk on the #testing slack channel, about the docker provisioner not really handling image names that doesn't conform to the form of containing the distribution name as part of the image name and the distribution version as the tag.  This is a show stopper for using the `centos/systemd:latest` image and possibly other internal company images as well.
It also formed around me trying to use podman for running the containers in user space.
The initial attempt just reads the `/etc/os-release` file and parses out the `ID` and `VERSION_ID`.  This is far from perfect, but it is better than splitting the image name and tag apart.  The obvious problems are if the OS is too old to use `/etc/os-release`, like EL6 systems, or for example Debian testing, which currently doesn't …

docker: support podman; improve handling of OS distribution/version for non-litmusimage images

---

tasks/docker.rb

When rebasing #112, I didn't notice that the command would retrieve a different id for amazon linux. This change updates the `when`s to the new id.
Thanks to @da-ar for reporting the issue promptly.

Fix amazonlinux detection

---

tasks/docker.rb

If the new updated command fails the code will instead default to the previous method. This is necesary as Centos 6 does not support the new method.

(IAC-1227) fallback to imagename-based platform calculation for images that don't have `/etc/os-release`

---

tasks/docker.rb

As of #112 the way in which the ID for the image is retrieved has been changed causing Oracle Linux's id to be returned as `ol` rather than `oracle`, this is a quick PR to fix it to expect the correct value.

(IAC-1229) - Fix for Docker Oracle Linux

---

tasks/docker.rb

Previous PR #134 updated `oracle` to `ol` to account for new method of retrieving details, however this new method does not work for Oracle 6 and so `oracle` must be added back to the check.

(maint) - Fix for Docker Oracle Linux 6

---

tasks/docker.rb

When attempting to provision an image from a repository with a `/`
in the name (e.g. registry.suse.com), the provisioning will fail
because docker does not support `.`s in the image name.
This change updates the `gsub` call in the image name construction
to also substitute out `.`.
We should also be escaping the `/` character too - fixes that too

(MAINT) Update Docker provisioner image name gsub with '.'

---

README.md
tasks/docker.rb

Prior to this PR, there was no way to pass command-line arguments to
the docker run command in the docker provisioner. This PR adds the
ability to pass arguments to the docker run command through the existing
vars parameter. This PR resolves #142 
It also includes a small readme update to replace `--nodes` with `--targets`. Let me know if you would prefer this in a separate PR.
An example of this is below. 
```
$ bolt --modulepath .. task run provision::docker --targets localhost action=provision platform=litmusimage/centos:7 inventory=. vars='{ "docker_run_opts": ["-p 8086:8086", "-p 3000:3000"]}'
Started on localhost...
Finished on localhost:
{ 
"status": "ok",
"node_name": "localhost:2223",
"node": {
"uri": "localhost:2223",
"config": {
"transport": "ssh",
"ssh": {
"user": "root", …
```

(feat) Allow for passing docker runtime options

---

tasks/docker.rb

`include?` takes only strings, not regex
This addresses the failure in https://travis-ci.com/github/puppetlabs/puppet_litmus/jobs/462473050#L1535

Fix typo from rubocop fixes in docker provisioner

---

tasks/provision_service.rb

This work is to allow the addiiton of 'vars' into the inventory file for gcp provisioning, as required by comply. Tested against https://github.com/puppetlabs/comply/runs/1656251077?check_suite_focus=true with the following result:
Run cat ./inventory.yaml
```
---
version: 2
groups:
- name: docker_nodes
targets: []
- name: ssh_nodes
targets:
- uri: 104.155.47.124
config:
transport: ssh
ssh:
user: litmuskww5w1fm
password: ******************
host-key-check: false
port: 22
run-as: root
facts:
provisioner: provision::provision_service
platform: centos-7
uuid: 197d8ae6-027f-4b5f-b4c9-1509dffd0e5a
vars:
role: pe
- uri: 34.76.79.34
config:
transport: ssh
ssh:
user: litmusiyvs9lpg
password: ****************
host-key-check: false
port: 22
run-as: root
facts:
provisioner: …
```

(CISC-973) Handle vars in gcp provisioner

---

tasks/install_pe.sh

2019.8 console is significantly different from 2019.3
`-y -c ./conf.d/pe.conf` added so that PE installs unattended and with provided defaults

(maint) Update default PE to 2019.8

---

tasks/docker_exp.json
tasks/docker_exp.rb

Make the `docker_exp` provisioner work in the same way as the `docker` provisioned. See also puppetlabs/puppet_litmus#358. To make it more consistent also remove the old way of doing things from the `docker_exp` provider. 
This PR will also be accompanied by a PR on puppetlabs/puppet_litmus.

Docker run opts

---

tasks/abs.rb
tasks/docker.rb
tasks/docker_exp.rb
tasks/provision_service.rb
tasks/vagrant.rb

- Renaming the inventory.yaml file to litmus_inventory.yaml
- Relocating file from the module root directory to /spec/fixtures/
- Removal of vmpooler as it is deprecated
The point in this change is to avoid running tests on a live production system by accident.
This piece of work includes changes in multiple places. 
1. pdk-templates: https://github.com/puppetlabs/pdk-templates/pull/414
2. puppet_litmus: https://github.com/puppetlabs/puppet_litmus/pull/396
3. provision module: https://github.com/puppetlabs/provision/pull/161
The follow PR is testing out my changes: https://github.com/puppetlabs/puppetlabs-testing/pull/353

(GH-380) Moving inventory.yaml to /spec/fixtures/litmus_inventory.yaml

---

tasks/abs.rb

Was running into a problem where ABS was returning 404s that looked to
trace back to errors like:
Failed to allocate resources: Error ("OndemandVmpoolerAllocator Could
not allocate VMs because of a conflict: request_id 'iac-task-pid-496'
has already been created 409 Conflict") encountered while allocating
resources from
https://vmpooler-cinext.delivery.puppetlabs.net/api/v1/ondemandvm with
request [{"centos-8.3-kurl-beta-x86_64":1,"r
equest_id":"iac-task-pid-496"}]
Samuel's guess was that the issue was tripping over duplicate process
ids from previous runs. Adding timestamp to the submitted job_id to
avoid that.

(REPLATS-169) Add a timestamp to abs job_id

---

tasks/abs.rb

Allows for an ABS_SSH_PRIVATE_KEY env variable to provide a path to a
local private key for the inventory ssh config rather than a password
credential. Prefers ABS_SSH_PRIVATE_KEY if present.
This allows us to use ssh keys to reach abs hosts in CI.
I've been testing with my branch here:
https://github.com/puppetlabs/kurl_test/pull/47/files#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8R36

(feat) Add ssh key support to abs ssh transport

---

tasks/abs.rb

When `ABS_SSH_PRIVATE_KEY` is not set, `ENV['ABS_SSH_PRIVATE_KEY']` returns nil. Fixes the test for whether it's set to allow for a nil value.

(bug) Fix abs checkout when 'ABS_SSH_PRIVATE_KEY' is unset

---

tasks/abs.rb
tasks/docker_exp.rb

There were two error messages in the abs and docker_exp that probably
had a copy/pasted reference to facter_task/failure. Changed them to be
provision specific so it's clear when getting errors from one of the
tasks that it's coming from provision.

(maint) Change references to facter_task to be provision

---

Gemfile
spec/tasks/abs_spec.rb
tasks/abs.rb

The abs.rb is refactored into a class that is executed only if the task
file is the executing program. This allows the spec to load the task and
manipulate the class while mocking externals. The webmock gem is used to
provide HTTP::Net mocking.
The spec is not exhaustive, but hopefully covers enough to validate that
the refactor didn't break the task, and that the bug I added in #182 is
patched.
It could be expanded, and could serve as a template for adding specs
for other tasks in the module.
It does look to expose an edge case bug of calling the provision task
with an inventory directory specified that contains a pre-existing
inventory file.

(maint) Add a spec case for the provision::abs task

---

Gemfile
spec/tasks/abs_spec.rb
tasks/abs.rb

The provision::abs task was hardcoded to
abs-prod.k8s.infracore.puppet.net. This made it impossible to use the
task to test a new vm available from abs-stage.k8s.infracore.puppet.net
prior to making it live in abs-prod.
Since the allowed parameters for the task tie into the api expected by
Litmus, I added another environment variable here to allow selection of
the subdomain. I didn't allow selection of the entire fqdn because
having your vm source change entirely based on a hidden env variable
seemed dubious to me.
---
This is based on top of #186 for test coverage. We could either merge this and close that, or merge that and I'll rebase this...

(maint) Allow setting of abs subdomain

---

lib/task_helper.rb
spec/tasks/abs_spec.rb

I introduced this in cd72bb6.
When the newly structured abs task calls lib/task_helper's
get_inventory_hash() method and finds a pre-existing inventory_full_path
file. It attempts to call
PuppetLitmus::InventoryManipulation.inventory_hash_from_inventory_file()
which fails, because that method is not a class method.
The puzzling thing about this is why it ever worked, because I was wrong
that #187 was pre-existing.
The issue here is that the abs (the previous version), docker,
docker_exp, and vagrant tasks all use 'include PuppetLitmus::InventoryManipulation'
or 'include PuppetLitmus' (which includes InventoryManipulation) in the
scope of global functions declared implicitly on the main Object. This
causes the included module to be included in the base Object class,
which effectively makes …

(GH-187) Fixes abs failing provision if inventory file exists

---

tasks/abs.rb

We are seeing it quite regularly that it is taking over the 10min mark to provision all the vms for the compliance demo environment so have introduced an env var that can be used to account for this. Tested as shown below and working as expected;
**POLL_ABS_TIMEOUT_SECONDS=30** 
```
Starting: plan comply_demo::demo_01_provision_machines
Starting: task provision::abs on localhost
Finished: task provision::abs with 1 failure in 37.03 sec
Finished: plan comply_demo::demo_01_provision_machines in 37.04 sec
Failed on localhost:
Timeout: unable to get a 200 response in 30 seconds
Failed on 1 target: localhost
```
**unset POLL_ABS_TIMEOUT_SECONDS**
```
Starting: plan comply_demo::demo_01_provision_machines
Starting: task provision::abs on localhost
Finished: task provision::abs with 0 failures …
```

Add ENV var for ABS Polling Duration

---

README.md
tasks/docker.rb
tasks/docker_exp.rb

Continuation of https://github.com/puppetlabs/provision/pull/198.
Thanks for your contribution on this one @Sharpie :-)

(Maint) - remove deb family system volume

---

.github/workflows/auto_release.yml
.github/workflows/release.yml

Prior to this commit, provision didn't have the release_prep or release workflows. This commit adds them.

(CONT-941) Add release workflows

---

tasks/install_puppetserver.sh

This commit switches the RPM URL to pull from the top level link, as Puppet 8 does not have a convenience link located in the `puppet8` dir.

(MAINT) Support Puppet 8

---

tasks/docker.rb

Ubuntu/Debian images broken at provisioning
line 184 and 186 us \!docker_run_opts.include instead of \!docker_run_opts.include?

Fixed: tasks/docker.rb

---

.sync.yml
Gemfile
Rakefile

Prior to this commit, the release prep workflow intorduced was failing due to an incorrect version of the changelog generator. This commit pins it in the sync.yml and a pdk update was run.

(CONT-954) Pin changelog generator to 1.15.2

---

tasks/abs.rb
tasks/docker.rb
tasks/docker_exp.rb
tasks/vagrant.rb

This PR adds a `connect-timeout` flag to each provisioned node in the litmus_inventory, to help prevent transient timeout errors during testing.
Initially, this defaulted to 10s which caused numerous false errors due to timeouts, this increases the default to 2 minutes.
_note - machines provisioned with the provision_service will be updated in a separate PR in [provision_service](https://github.com/puppetlabs/provision_service)_

(maint) - Add connect-timeout to transport

---

.rubocop_todo.yml
spec/tasks/abs_spec.rb
spec/tasks/provision_service_spec.rb
tasks/provision_service.rb

We have seen multiple failures where the response is not expected but the response code is 200, so while parsing it fails which lead to pipeline failure.
So added retry when response is empty or while parsing it fails.
Eg : https://github.com/puppetlabs/puppetlabs-lvm/actions/runs/5639289396/job/15274332392
- N/A
- N/A

(CONT-1241) - Retrying when response body is nil or empty but response code is 200

---

.changelog.yml
.github/workflows/release_prep.yml
CHANGELOG.md

Updating release workflow with reusable workflows.
N/A
N/A

(MAINT) Updating release workflows with reusable workflows

---

tasks/vagrant.rb

Fixes https://github.com/puppetlabs/provision/issues/227

(CAT-1253) - Fixes undefined variable in vagrant provisioner

---

metadata.json

Drop support for OS no longer supported by puppet agent.
refer [here](https://www.puppet.com/docs/pe/2023.2/supported_operating_systems.html#supported_operating_systems_and_devices-supported-agent-platforms).

(CAT-1264) - Drop Support for EOL Windows 2008 R2, Debian 8 + Ubuntu 16.04

---

metadata.json

(CAT-1264) - Add Support for CentOS 8, RHEL 8/9, Debian 10/11, Ubuntu 18/20/22, Windows 16/19/22

---

.github/workflows/ci.yml
.github/workflows/nightly.yml

this module incorrectly used the gem ci testing.
this Pr updates to use the module CI testing instead.

(maint) - Update to use module ci

---

README.md

(maint) - Update README

---

tasks/run_tests.json
tasks/run_tests.rb

This commit parameterizes the RSpec testing format in the `provision::run_tests` task to allow users to specify either `progress` (**default**) or `documentation`.
- The current implementation of the task only allows for RSpec **progress** output which prints dots (`.`) for passing examples, `F` for failures, `*` for pending. As a user I would like to see more verbose output from the tests I am running. The **documentation** output prints the docstrings passed to `describe` and `it` methods.
- As the task currently hardcodes output to **progress**, I have ensured this is the default parameter value.

(MAINT) RSpec testing format parameter

---

tasks/vagrant.rb

Determining the SSH service restart command needed based on the Vagrant box name containing one of the expected sequences is problematic. With this change the required service restart command should be automatically determined for at least all vaguely recent Debian, Ubuntu, EL, or Suse systems, regardless of box name.

Add flexible Linux box support for Vagrant

---

tasks/docker.rb

- Add support for EL 9 containers with or without systemd as init. Tested with:
-  quay.io/almalinuxorg/9-base
-  quay.io/almalinuxorg/9-init
-  quay.io/rockylinux/rockylinux:9-ubi
-  quay.io/rockylinux/rockylinux:9-ubi-init
- Add support for SLES 15 (and possibly 12) containers with or without systemd as init. Tested with:
- registry.suse.com/bci/bci-init:15.5
- registry.suse.com/suse/sle15:15.5
For the EL 9 changes, in testing I found that the `yum install` command would often not complete successfully when using an init image.  The root cause seems to be some type of race condition where during systemd startup /var/cache/dnf is not always available by the time yum (dnf) is invoked, causing an error such as `[Errno 2 No such file or directory: '/var/cache/dnf/metadata_lock.pid'` during …

Add additional Docker provisioner OS support

---

README.md
tasks/docker.rb

Adds support for parsing the docker context or DOCKER_HOST environment variable to determine the hostname used to connect to the instance.

docker context and DOCKER_HOST env support

---

tasks/docker.rb

Fixes distro match in the `install_ssh_components` method expects `redhat`, but `ID` from os-release is actually `rhel`.
Without this, redhat universal base containers are unable to provision.

fix redhat distribution not supported

---

tasks/docker.rb

Suse containers with ssh already installed fail to provision when the task attempts to create host keys that already exist.

fix sles ssh setup in docker if ssh already installed

---

lib/docker_helper.rb
lib/task_helper.rb
spec/unit/docker_helper_spec.rb
tasks/docker.json
tasks/docker.rb
tasks/docker_exp.json
tasks/docker_exp.rb

Commits are simply housekeeping. Reconcile the two docker tasks to ensure they create containers and manage the bolt inventory in exactly the same way. After this I'm hoping we can move to supporting unprivileged docker containers.
These changes can be tested running the [manual workflow on Litmusimage](https://github.com/puppetlabs/litmusimage/actions/workflows/manual.yml) using `{ "git": "https://github.com/h0tw1r3/provision.git", "ref": "docker-dodo" }` for the _provision module_ option after https://github.com/puppetlabs/litmusimage/pull/75 is merged.

Cleanup docker support

---

tasks/docker.rb

rockylinux images recently dropped yum. other distros are likely to do the same.
observed failures in litmusimage nightly smoke tests

fix provision on dnf only platforms

---

README.md
spec/tasks/vagrant_spec.rb
tasks/vagrant.json
tasks/vagrant.rb

To use multi-node provisioning locally with vagrant we need to be able to
assign arbitrary tags to the nodes we deploy.
Other provisioners do this with a parameter called vars.
This PR introduces support for this, and essentially copies what is
already present in the other bolt tasks in this module.
Litmus
```
bundle exec rake 'litmus:provision[vagrant, generic/debian10, role: worker1]'
```
Bolt
```
bundle exec bolt task run provision::vagrant --targets localhost  action=provision platform=generic/debian10 vars='role: worker1'
```
Will return an inventory file like
```
- uri: 127.0.0.1:2200
config:
transport: ssh
ssh:
user: vagrant
host: 127.0.0.1
host-key-check: false
port: 2200
run-as: root
connect-timeout: 120
private-key: "path/vagrant.key.ed25519"
facts:
provisioner: vagrant …
```

(CAT-372) - add var support to vagrant provisioner

---

lib/task_helper.rb
spec/tasks/lxd_spec.rb
tasks/lxd.json
tasks/lxd.rb

Goal is to get puppet litmus working with LXD / Incus.

LXD provisoner support

---

.github/workflows/ci.yml
README.md
lib/task_helper.rb
plans/provisioner.pp
plans/teardown.pp
spec/tasks/abs_spec.rb
spec/tasks/vagrant_spec.rb
tasks/abs.rb
tasks/docker.rb
tasks/docker_exp.rb
tasks/lxd.rb
tasks/provision_service.rb
tasks/vagrant.rb

tasks document the inventory parameter as the "location to inventory file", so make it behave as such.
changes are backwards compatible with puppet_litmus <= 1.3.0
_this is the beginning of uncoupling the litmus specific assumptions in the provision module._

tasks require path to inventory yaml

---

README.md
lib/docker_helper.rb
lib/inventory_helper.rb
lib/task_helper.rb
spec/spec_helper_local.rb
spec/tasks/abs_spec.rb
spec/tasks/lxd_spec.rb
spec/tasks/provision_service_spec.rb
spec/tasks/vagrant_spec.rb
spec/unit/docker_helper_spec.rb
spec/unit/inventory_helper_spec.rb
tasks/abs.json
tasks/abs.rb
tasks/docker.json
tasks/docker.rb
tasks/docker_exp.json
tasks/docker_exp.rb
tasks/lxd.json
tasks/lxd.rb
tasks/provision_service.json
tasks/provision_service.rb
tasks/vagrant.json
tasks/vagrant.rb

__Requesting feedback__
Transforms this pseudo puppet module (which requires a gem not bundled with anything) into an standard r10k/bolt installable module usable outside of the litmus framework.
Module is very useful outside of litmus, particularly for real-time puppet code development. Provision a node, do some "live" development and testing, tear it down.

Uncouple from the puppet_litmus gem

---

tasks/docker.rb
tasks/docker_exp.rb
tasks/provision_service.rb
tasks/vagrant.rb

puppet_litmus gem is passing the target uri as the node_name param, which causes an InventoryHelper.lookup exception.
- Easily reproducible by following the standard litmus testing workflow with the docker, docker_exp, or vagrant backends. Provisioning and testing works fine, but litmus:tear_down throws an exception.
- By using the unnamed param to lookup instead of `name`, lookup will automatically search for a matching target uri, or name value.

fix tear_down from puppet_litmus

---

tasks/abs.rb

This alters the request body payload object to correctly reference the node job id which is required for tear_down of an abs node.
Before: 
```
bundle exec rake 'litmus:tear_down'                                                                                  
HEAD is now at c511041 Merge pull request #647 from puppetlabs/release-prep
rake aborted!
tear_down of our_abs_node.net failed.
Results:
localhost: {"_error"=>{"kind"=>"provision/abs_failure", "msg"=>"Error: #<Net::HTTPNotFound:0x000000010c2d98a0>: Not Found", "details"=>{}}}}
/Users/jordan.breen/Desktop/repos/modules/puppetlabs-motd/.bundle/gems/ruby/3.2.0/gems/puppet_litmus-1.4.0/lib/puppet_litmus/rake_helper.rb:335:in `raise_bolt_errors'
/Users/jordan.breen/Desktop/repos/modules/puppetlabs-motd/.bundle/gems/ruby/3.2.0/gems/puppet …
```

(CAT-1958) - Fix 404 on teardown of abs node

---

tasks/provision_service.rb

this provides a default inventory location in the event that one is not supplied to the provision service task.

(bug) - Fix empty inventory

---

.github/workflows/ci.yml

Shellcheck has been moved to our reusable workflows repository and is
now part os our CI testing. As such, we are removing the action from
here and enabling it to be called.

(CAT-2094) Reusable shellcheck

---

tasks/install_puppetserver.sh

Upon adding Ubuntu 22.04 to our test matrix I discovered that the `install_puppetserver` task does not support the aforementioned OS.
As such, this commit includes changes to ensure Ubuntu 22.04 is recognized and the package is pulled and installed.
- Current code is missing the codename for Ubuntu 22.04 and returns an error stating that there are no build available for the OS.

(MAINT) Support for Puppet Server on Ubuntu 22.04

---

tasks/install_puppetserver.json
tasks/install_puppetserver.sh

This commit corrects a syntax issue causing the `provision::install_puppetserver` task to fail on the Ubuntu platform.
The arguments for the `fetch_codename()` function are currently grouped to be passed in as a single argument instead of **`$collection`** and **`$platform`** separately. As a result the task errors out and states there are no builds for Ubuntu.
Looks like the issue was introduced in this [commit](https://github.com/puppetlabs/provision/commit/0b87fad0ab0a84a4f02a0f6ec0688cf4811c51ef).

(MAINT) Install Puppet Server Task

---

tasks/install_pe.json
tasks/install_pe.sh

Add parameter to specify os bundle that will be downloaded from artifactory.
Currently hardcoded to `el-7-x86_64` and have kept this as default
We could dynamically determine os distro/version but this is just a quick fix for now.
N/A

(PE-39952) Add PE os version

---

.github/workflows/ci.yml
Gemfile
metadata.json
spec/integration/puppetcore_spec.rb

This PR introduces puppetcore gem source integration to the provision module. When `PUPPET_FORGE_TOKEN` environment variable is set, the module will use authenticated puppetcore gem sources; otherwise, it will default to public gem sources. This implementation follows the "switch" design pattern to ensure all modules work correctly regardless of whether puppetcore is used or not.
- `Gemfile`: Implemented conditional logic to use puppetcore gem source when `PUPPET_FORGE_TOKEN` is set
- `ci.yml` workflow: Updated to use Ruby 3.1+ which is required for puppetcore gems.  This workflow "uses" the shared cat-github-actions workflow that was updated in this PR: https://github.com/puppetlabs/cat-github-actions/pull/129
- `metadata.json`: Updated Puppet version requirement to 8.0.0+ to align with …

feat(puppetcore): Add puppetcore gem source switch capability

---

.rubocop.yml
Gemfile
spec/tasks/lxd_spec.rb
spec/tasks/vagrant_spec.rb
tasks/lxd.rb
tasks/provision_service.rb
tasks/update_node_pp.rb
tasks/update_site_pp.rb
tasks/vagrant.rb

Puppet 7 is EOL. Therefore, we can remove the test infrastructure for it. This commit aims to clear up any testing/config infrastructure related to Puppet 7 and, by extension, Ruby 2.7. Bumping rubocop TargetRubyVersion to 3.1 and applying safe autocorrections.

(CAT-2286) Remove puppet 7 infrastructure
